### ISSUE TITLE
What library should be used now?

### ISSUE THREAD

**Issue by ghost** [lang/unicode_utils#1]
Hello, this library doesn't seem to be maitained anymore (no more commit) - which solution would you now recommand for unicode normalization under Ruby 1.9?

**Comment by lang** [comment]
There are no recent commits because

a) I didn't encounter a bug recently

b) Nobody reported a bug recently

c) It does what I need so far :-)

This lib just implements a couple standardized Unicode
algorithms that rarely change, it's not something that needs
constant development :-)

It's 1.0, you can use it and report if you have problems.
